### ISSUE TITLE
Does it still work? Tried running it

### ISSUE THREAD

**Issue by shortside** [hldh214/buff2steam#15]
When I run it, it asks me with what program i want to open. 
After I select anything i just opens a empty file.

**Comment by shortside** [comment]
Got it working, but i got 1 result and after that I got an error:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\stef_\Desktop\buff2steam-0.0.1\buff2steam-ng\buff2steam\__main__.py", line 99, in <module>
    main()
  File "C:\Users\stef_\Desktop\buff2steam-0.0.1\buff2steam-ng\buff2steam\__main__.py", line 95, in main
    trio.run(trio_wrapper)
  File "C:\Users\stef_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\trio\_core\_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "C:\Users\stef_\Desktop\buff2steam-0.0.1\buff2steam-ng\buff2steam\__main__.py", line 89, in trio_wrapper
    await _main(config)
  File "C:\Users\stef_\Desktop\buff2steam-0.0.1\buff2steam-ng\buff2steam\__main__.py", line 56, in _main
    orders_data = await steam.orders_data(market_hash_name)
  File "C:\Users\stef_\Desktop\buff2steam-0.0.1\buff2steam-ng\buff2steam\provider\steam.py", line 55, in orders_data
    item_nameid = self.item_nameid_pattern.findall(res.text)[0]
IndexError: list index out of range
C:\Users\stef_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\httpx\_client.py:1772: UserWarning: Unclosed <httpx.AsyncClient object at 0x0000025C84AE2F70>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.

**Comment by hldh214** [comment]
Can you try latest commit and see if still have issue?
